zabbixAgent:
  enabled: true
  env:
    - name: ZBX_PASSIVE_SERVERS
      value: 0.0.0.0/0
zabbixProxy:
  enabled: true
  env:
    - name: ZBX_HOSTNAME
      value: zabbix-proxy
    - name: ZBX_SERVER_HOST
      value: "zabbix-zabbix-server.monitoring:10051"
    - name: ZBX_CACHESIZE
      value: 256M
    - name: ZBX_VALUECACHESIZE
      value: 128M
    - name: ZBX_CONFIGFREQUENCY
      value: 60
