apiVersion: v1
kind: PersistentVolume
metadata:
  name: crate-pv-0
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.40.100
    path: /mnt/nfs_share/crate/crate-0
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crate-pv-1
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.40.100
    path: /mnt/nfs_share/crate/crate-1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crate-pv-2
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.40.100
    path: /mnt/nfs_share/crate/crate-2
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-crate-0
spec:
  storageClassName: ""
  volumeName: crate-pv-0
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-crate-1
spec:
  storageClassName: ""
  volumeName: crate-pv-1
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-crate-2
spec:
  storageClassName: ""
  volumeName: crate-pv-2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
