apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-tls-alldcs
  namespace: observability
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana-prod.alldcs.nl`)
    kind: Rule
    services:
    - name: kube-prom-stack-grafana
      port: 80
  tls:
    certResolver: letsencrypt
