apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
  namespace: monitoring
data:
  zabbix_agent2.conf: |
    PidFile=/run/zabbix/zabbix_agent2.pid
    LogFile=/var/log/zabbix/zabbix_agent2.log
    LogFileSize=0
    Server=zabbix-server
    ServerActive=zabbix-server
    HostnameItem=system.run[echo $NODE_NAME]
    ListenIP=0.0.0.0
