apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-tls
  namespace: tekton-pipelines
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`tekton-dev.allarddcs.nl`)
    kind: Rule
    services:
    - name: tekton-dashboard
      port: 9097
  tls:
    certResolver: letsencrypt
