apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: acme-challenge
  namespace: cert-manager
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/\.well-known/acme-challenge/`)
      kind: Rule
      services:
        - name: cert-manager
          port: 80
