apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kafka-tls
  namespace: kafka
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`kafka-ui-prod.allarddcs.nl`)
    kind: Rule
    services:
    - name: kafka-ui
      port: 8080
  tls:
    certResolver: letsencrypt
