apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-tls
  namespace: observability
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana-dev.allarddcs.nl`)
    kind: Rule
    services:
    - name: kube-prom-stack-grafana
      port: 80
  tls:
    certResolver: letsencrypt
