apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
stringData:
  config.json: |
    {
      "auths": {
                "harbor.alldcs.nl": {
                        "auth": "YWRtaW46SGFyYm9yMDFA"
                }
        }
    }
