apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: registry-tcp-tls
  namespace: nexus
spec:
  entryPoints:
  - websecure
  routes:
  - match: HostSNI(`registry-dev.alldcs.nl`)
    services:
    - name: nexus
      port: 8444
  tls:
    passthrough: true
