apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forwarded-headers
spec:
  headers:
    customResponseHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-For: "{remote}"
      X-Real-IP: "{remote}"
