apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: quickstart-tls-dialdcs
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`elastic.dialdcs.com`)
    kind: Rule
    services:
    - name: quickstart-kb-http
      port: 5601
    middlewares:
      - name: kibana-replace-url
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: quickstart-tls-alldcs
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`elastic.alldcs.nl`)
    kind: Rule
    services:
    - name: quickstart-kb-http
      port: 5601
    middlewares:
      - name: kibana-replace-url
  tls:
    certResolver: letsencrypt
