apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: percona-route-tcp-tls
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`percona.alldcs.nl`)
    services:
    - name: percona-pmm
      port: 443
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: percona-route-tcp-http
spec:
  entryPoints:
    - web
  routes:
  - match: HostSNI(`percona.alldcs.nl`) 
    services:
    - name: percona-pmm
      port: 80

