apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-tls
  namespace: observability
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`prometheus-prod.allarddcs.nl`)
    kind: Rule
    services:
    - name: kube-prom-stack-kube-prome-prometheus
      port: 9090
  tls:
    certResolver: letsencrypt
