apiVersion: v1
kind: Service
metadata:
  name: camunda
  namespace: camunda
spec:
  selector:
    app: camunda
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  namespace: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda
          image: allardkrings/camunda7-arm64v8
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: camunda-tls
  namespace: camunda
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`camunda-prod.allarddcs.nl`)
    kind: Rule
    services:
    - name: camunda
      port: 8080
  tls:
    certResolver: letsencrypt
