apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wordpress-http
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`wordpress.alldcs.nl`)
    kind: Rule
    middlewares:
      - name: redirect-to-https
    services:
    - name: wordpress
      port: 80
