apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-http
  namespace: nginx
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`nginx-riscv.allarddcs.nl`)
    kind: Rule
    services:
    - name: nginx
      port: 80
