apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry-tls
  namespace: nexus
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`registry-dev.allarddcs.nl`)
    kind: Rule
    services:
    - name: nexus
      port: 8444
  tls:
    certResolver: letsencrypt
