apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nexus-tcp-tls
  namespace: nexus
spec:
  entryPoints:
  - websecure
  routes:
  - match: HostSNI(`nexus-dev.allarddcs.nl`)
    services:
    - name: nexus
      port: 8443
  tls:
    passthrough: true
