apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: argocd-route-tcp-tls
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`argocd-dev.allarddcs.nl`)
    priority: 10
    services:
    - name: argocd-argo-cd-server
      port: 443
#  - match: HostSNI(`argocd.alldcs.nl`) && Headers(`Content-Type`, `application/grpc`)
#    priority: 11
#    services:
#    - name: argocd-argo-cd-server
#      port: 443
  tls:
    passthrough: true

