apiVersion: v1
kind: Service
metadata:
  name: prod-http
  namespace: traefik
spec:
 ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prod-http
  namespace: traefik
subsets:
  - addresses:
    - ip: 192.168.2.191
    ports:
    - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prod-http
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - match: HostRegexp(`^[a-z0-9]+-prod\.allarddcs\.nl$`)
    kind: Rule
    services:
    - name: prod-http
      port: 80
