apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: traefik
spec:
 ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitea-http
  namespace: traefik
subsets:
  - addresses:
    - ip: 192.168.2.181
    ports:
    - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-http
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`gitea-dev.allarddcs.nl`)
    kind: Rule
    services:
    - name: gitea-http
      port: 80
  - match: Host(`gitea-dev.allarddcs.nl`) && PathPrefix(`/.well-known/acme-challenge/`)
    kind: Rule
    services:
    - name: gitea-http
      port: 80
