apiVersion: v1
kind: Service
metadata:
  name: riscv-tls
  namespace: traefik
spec:
  type: ExternalName
  externalName: 192.168.2.113
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: riscv-tls
  namespace: traefik
subsets:
  - addresses:
    - ip: 192.168.2.113
    ports:
    - port: 443
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: riscv-tls
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - match: HostSNIRegexp(`^[a-z0-9]+-riscv\.allarddcs\.nl$`)
    services:
    - name: riscv-tls
      port: 443
  tls:
    passthrough: true
