apiVersion: v1
kind: Service
metadata:
  name: dev-http
  namespace: traefik
spec:
 ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dev-http
  namespace: traefik
subsets:
  - addresses:
    - ip: 192.168.2.181
    ports:
    - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dev-http
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
    - match: HostRegexp(`^[a-z0-9]+-dev\.allarddcs\.nl$`) 
      kind: Rule
      services:
        - name: dev-http
          port: 80
