apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-workspace-pvc
spec:
  storageClassName: ""
  volumeName: buildah-workspace-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi



