apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah-clone-build-push
spec:
  workspaces:
    - name: myworkspace
    - name: dockerconfig-ws
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: myworkspace
      params:
        - name: url
          value: https://github.com/AllardKrings/helloallard.git
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      params:
        - name: IMAGE
          value: harbor.alldcs.nl/allard/helloallard:1.0
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: myworkspace
        - name: dockerconfig
          workspace: dockerconfig-ws
