apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-0
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.2.110
    path: /mnt/nfs_share/redis/master-0
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-replicas-0
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.2.110
    path: /mnt/nfs_share/redis/replicas-0
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-replicas-1
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.2.110
    path: /mnt/nfs_share/redis/replicas-1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-replicas-2
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.2.110
    path: /mnt/nfs_share/redis/replicas-2
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-master-0
  namespace: redis
spec:
  storageClassName: ""
  volumeName: redis-master-0
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-replicas-0
  namespace: redis
spec:
  storageClassName: ""
  volumeName: redis-replicas-0
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-replicas-1
  namespace: redis
spec:
  storageClassName: ""
  volumeName: redis-replicas-1
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-replicas-2
  namespace: redis
spec:
  storageClassName: ""
  volumeName: redis-replicas-2
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

