#apiVersion: traefik.containo.us/v1alpha1
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: argo-workflows-tcp-tls
  namespace: argo
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`argo-riscv.allarddcs.nl`)
    services:
    - name: argo-server
      port: 2746
  tls:
    passthrough: true

