apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: site
  name: site
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: site
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: site
    spec:
      containers:
        - args:
            - server
          image: harbor.alldcs.nl/allard/tekton-example:1.0
          name: site
          ports:
            - containerPort: 1313
          resources: {}
          volumeMounts:
            - mountPath: /src
              name: site-claim0
      restartPolicy: Always
      volumes:
        - name: site-claim0
          persistentVolumeClaim:
            claimName: site-claim0
status: {}
