apiVersion: apps/v1
kind: Deployment
metadata:
  name: olproperties
  labels:
    app: olproperties
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olproperties
  template:
    metadata:
      labels:
        app: olproperties
    spec:
      containers:
      - name: olproperties
        image: harbor-dev.allarddcs.nl/allard/olproperties:1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
      imagePullSecrets:
      - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: olproperties
spec:
  type: ClusterIP
  ports:
  - name: port-0
    port: 9080
  selector:
    app: olproperties
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: olproperties-tls
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`olproperties-dev.allarddcs.nl`)
    kind: Rule
    services:
    - name: olproperties
      port: 9080
  tls:
    certResolver: letsencrypt

