apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: defectdojo-tls
  namespace: defectdojo
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`defectdojo-dev.allarddcs.nl`)
    kind: Rule
    services:
    - name: defectdojo-django
      port: 80
  tls:
    certResolver: letsencrypt
