apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: quay-tcp
  namespace: quay
spec:
  entryPoints:
  - websecure
  routes:
  - match: HostSNI(`quay-lp.alldcs.nl`)
    services:
    - name: quay
      port: 443
  tls:
    passthrough: true

