apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-lp.allarddcs.nl-tls
  namespace: kube-system
spec:
  dnsNames:
  - kubernetes-lp.allarddcs.nl
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: kubernetes-lp.allarddcs.nl-tls
  usages:
  - digital signature
  - key encipherment
