apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-k8s-binding
subjects:
  - kind: ServiceAccount
    name: default # or your Backstage SA
    namespace: backstage
roleRef:
  kind: ClusterRole
  name: backstage-k8s
  apiGroup: rbac.authorization.k8s.io
