apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitea-tcp-http
  namespace: gitea
spec:
  entryPoints:
  - web
  routes:
  - match: HostSNI(`gitea-dev.allarddcs.nl`)
    services:
    - name: gitea
      port: 3000
